### ISSUE TITLE
Add option to not return NULL values

### ISSUE THREAD

**Issue by elvis197686** [RedisLabsModules/RedisGraph#354]
The fact that RedisGraph returns null values as strings with the value "null" is a performance problem - it forces clients to filter out or transform that value.

We believe it would be better for RedisGraph to allow null values to not be returned - maybe as an additional keyword for the RETURN statement? It may be that we are missing something w.r.t null processing, so apologies if that is the case.

BTW, the RedisGraph manual states `To remove a node's property, simply set property value to NULL`, which I believe is misleading because, according to my testing with redis-cli, it still returns the property, but set as a null string as mentioned above.

**Comment by K-Jo** [comment]
Hi @elvis197686 
We're updating the response format of RedisGraph here: https://github.com/RedisLabsModules/RedisGraph/pull/339  We'll move away from a pure tabular structure in to a response of nodes and arrays where only the properties that exist will be returned.

**Comment by K-Jo** [comment]
hi @elvis197686 
We fixed this issue partially by #356 and will take this up further in our updated graph response story in #339.  The second part of this issue is related to the fact that the property still exists after deletion.  For this we created #363.  If you're ok with this, we'd like to close this issue

**Comment by elvis197686** [comment]
ok, you can close this issue
