### ISSUE TITLE
type(node) crashes redis

### ISSUE THREAD

**Issue by Jonahss** [RedisLabsModules/RedisGraph#360]
`MATCH (n) RETURN type(n)`  --> redis crashes

A dumb mistake to make, but probably shouldn't be catastrophic.

**Comment by Jonahss** [comment]
Also, now I'm just curious, why does `MATCH (n)-[r]->(m) RETURN labels(r)` return the label of `m`?

**Comment by swilly22** [comment]
Hi @Jonahss thank you for reporting.
Agree, the server shouldn't crash in this situation, we need to do a better job validating.
the odd behavior you're seeing is probably because edge `r` has the same ID as a node labeled as node m. [see source](https://github.com/RedisLabsModules/RedisGraph/blob/master/src/arithmetic/arithmetic_expression.c#L652)

**Comment by swilly22** [comment]
Crash fixed, although a better solution would be responding with a type mismatch error.

**Comment by Jonahss** [comment]
Cool :)
