### ISSUE TITLE
No result found when query with existing and non existing relationship

### ISSUE THREAD

**Issue by sandyk12** [RedisLabsModules/RedisGraph#361]
Please consider a graph below:

```
CREATE (:Person {name: 'A'})
CREATE (:Person {name: 'B'})
CREATE (:Person {name: 'C'})
CREATE (:Person {name: 'D'})

#A has 2 friends
MATCH (p:Person {name: 'A'}) CREATE (p)-[:friends]->(p1:Person {name: 'B'})
MATCH (p:Person {name: 'A'}) CREATE (p)-[:friends]->(p1:Person {name: 'C'})

#B has 2 friends
MATCH (p:Person {name: 'B'}) CREATE (p)-[:friends]->(p1:Person {name: 'C'})
MATCH (p:Person {name: 'B'}) CREATE (p)-[:friends]->(p1:Person {name: 'D'})

#C has 2 friends
MATCH (p:Person {name: 'C'}) CREATE (p)-[:friends]->(p1:Person {name: 'B'})
MATCH (p:Person {name: 'C'}) CREATE (p)-[:friends]->(p1:Person {name: 'D'})

#D has no friends
```

``` MATCH (p1:Person {name: 'A'}),(p2:Person {name: 'D'})-[f:friends]->(p3:Person) RETURN p3```

Result Set : No result

I belief above as in query so if A has friends but D does not have friends, so query should give result of A. But its giving no result.

Anyway we can achieve this.

**Comment by swilly22** [comment]
Hey @sandyk12 ,
Please note that in all of the MATCH CREATE queries you've presented,
e.g. `MATCH (p:Person {name: 'A'}) CREATE (p)-[:friends]->(p1:Person {name: 'B'})`
You're re-creating the destination node, in the example (p1:Person {name: 'B'}) is created and now we've got two Person nodes with name: 'B'.

This is because p1 in the example isn't matched against, and so it is created, I would suggest the following:
`MATCH (p:Person {name: 'A'}), (p1:Person {name: 'C'}) CREATE (p)-[:friends]->(p1)`

Now with regard to: `MATCH (p1:Person {name: 'A'}),(p2:Person {name: 'D'})-[f:friends]->(p3:Person) RETURN p3`

you're asking to return p3 which is a friend of person D, but D doesn't have any friends,
regardless, this query results in a cartesian product, where one side isn't matched, as such the result-set is empty.

Please try to describe what is it that you're trying to achieve and I'll do my best to help.

**Comment by sandyk12** [comment]
I am figuring out best way to find four person's (A,B,C,D) friends list without using or query
  
```MATCH (p1:Person)-[f:friends]->(p3:Person) Where (p1.name='A' or p1.name='B' or p1.name='C' or p1.name='D') RETURN p3```

Even I have indexed name its taking too much time.

Thats why trying like below
````MATCH (p1:Person {name: 'A'}),(p2:Person {name: 'D'})-[f:friends]->(p3:Person) RETURN p3```

**Comment by swilly22** [comment]
I see, current index implementation can't be utilised when filtering an indexed node using `OR`.
See execution-plan by using `Graph.Explain`
We're working on improving our index, such that `OR` filters will be supported.

Your best option currently to utilise the index is by using a cartesian product:
`GRAPH.query G "MATCH (A:Person {name:'A'})-[:friends]->(af), (B:Person {name:'B'})-[:friends]->(bf), (C:Person {name:'C'})-[:friends]->(cf)RETURN DISTINCT A,af, B,bf, C,cf"`

Note each `Person` must have at least one friend for this query to return records.
